name: deploy-multi-container-app

on:
  push:
    branches: 
      - main
      
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@v1
        
      - run: docker build -t flawwwless/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true flawwwless/react-test npm test
      
  build_prod:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Git clone repo
        uses: actions/checkout@v1
      
      - run: docker build -t flawwwless/multi-client ./client
      - run: docker build -t flawwwless/multi-nginx ./nginx
      - run: docker build -t flawwwless/multi-server ./server
      - run: docker build -t flawwwless/multi-worker ./worker
      # Log in to the docker CLI
      - name: Login to dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      # Take those images and push them to docker hub
      - run: docker push flawwwless/multi-client
      - run: docker push flawwwless/multi-nginx
      - run: docker push flawwwless/multi-server
      - run: docker push flawwwless/multi-worker
